### My Life ###

print('Welcome to the game MY LIFE ')
input()

Name=(input('select your calacter:a) Gabriel b) Iker c) Daniel '))
input()


if Name=="Gabriel":
  print("Hi" ,Name ,"click enter to start your life")
  input()
  print('Your caracteristics are: Singing and going to parties all days ')
  input()
  All=(input("Okey it's alredy night and you have to decide if you go to singing Lessons or go to party,a)Lessons or b)Party "))
  
  if All=="Lessons":
    input()
    print('In your singing class the teacher tells you to keep going and that you have talent and you can have a future')
    
    input()
    print('(As you now since you were little you were good at singing)')
    
    input()
    print('After several classes the teacher told you that you are going to participate in a contest ')
    
    input()
    print('You accept to participate in the contest ')
    print('at the beginning of the contest it gave you nerves but at the end...')
    
    input()
  
    print('YOU WIN')
    input()
    print('At the end of the contest a celebrity invites you to a party that night')
   
    input()
    print('And you accept')
   
    input()
    print('In that party there were people smoking and using drugs, and they ask you if you want to try it')
   
    input()
    print('You do not accept to try it and you tell them no because you can get to see ')
    input()
    print('The next day...')
   
    input()
    print('Your teacher tells you that he can no longer teach you more than what you already know and that you should go with someone more professional')
 
    input()
    print('You found a very good teacher but he lives in another city, and you decide that you are going to move out')
    input()
    print('in the new city you barely have enough to pay for the apartment so you have a problem')
    input()
    print('To solve the problem you have to decide if you should leave school and look for a job or stay in school(Click enter)')
    input()
    Mon=(input('What are you going to choose a)Work or b)School')) 
    if Mon=="Work":
      print('Since you decided to quit school, you got a job in the morning')
      print('and in the afternoons you have your singing classes')
      input()
      print('After many classes with your new teacher, he asks you if you plan to live from music?')
      input()
      print('and you say yes')
      input()
      print('Then since he is known he starts introducing you to famous people')
    
      input()
      print('Your teacher asked you what you were going to nickname yourself ')
      input()
      print('And you told him that your nickname was going to be bad dogg')
      input()
      print('And your teacher told you that you should start creating songs and that he would help you with the production ')
      input()
      print('When you finish writing the song your teacher helped you with the tools to record the song ')
      input()
     
      print('Seeing that you had talent, he offered you a deal and he was going to hire you a manager and technicians')
      print('Now the technicians help you upload your song to music platforms')
      input()
     
      print('After 1 week of releasing your first song, it was a success')
      input()
      print('How was the song a success your manager told you to do more songs')
      input()
      
      print('After many songs they start paying you')
      print('The bank give you the code of your card and it is :1234')
      input()
      print('You decide to release an album')
      print('and it was a success')
      input()
      print('After several years singing you are already a millionaire and decide to retire from music')
      input()
      print('you got old and you are dying and you decide to spend all your funds making a bad dog music school')
      input()
      print('You die happy because you do the school pf music.END GAME ')
  
    if Mon=="School":
      print('Because you decide to stay in school,you began to have more economic problems')
      input()
    
      print('and you no longer have enough to pay the teacher')
      input()
      print('After a month you no longer had enough money and you had to return to your city')
      input()
     
      print('When you finish the school in your country ')
      input()
      print('You start working in a company ')
      input()
      print('Being unhappy at your job, you decide to throw yourself out of your company building and...')
      input()
      print('You die, game over')
  if All=="Party":
    print('At the party you got drunk, but those who made the party liked you,that was the popular group ')
    input()
    print('After some parties and meetings coinciding, you started to be friend with some people of the popular  group')
    input()
    print('Now people from the popular group invite you to parties')
    input()
    print('After several parties together, they invite you to be part of their group')
    
    input()
    print('And you ACCEPT')
    input()
    print('At a party with them you meet a very cute girl,and you invite her on a date')
   
    input()
    print('After several dates with her, you ask her if she wants to be your girlfriend, and she tells you...')
    input()
    print('YES')
    input()
    
    print('In one party that  you went alone with your friends ')
    input()
    print('Your friends already trust on you they offered you drugs')
    input()
    print('And you accept')
    input()
   
    print('after several times trying drugs at parties or alone.Your girlfriend finds out')
   
    print('and she confronts you and tells you that you should get help or she breaks up with you(CLICK ENTER)')
    input()
    Hob=(input('Now you must choose: a)Help or b)Break')) 
    if Hob=="Help":
      print('For help you went to a psychologist')
      input()
      print('On your first appointment with the psychologist, she asked you a lot of questions and she scheduled your second appointment for tomorrow. ')
      input()
    
      print('On your second date the psychologist told you that you should leave your group of friends')
      input()
      print('You think that was a bad idea but you did it with the support of your girlfriend')
      input()
      print('After several appointments with the psychologist, she tells you that you should look for a job.')
      input()
   
      print('After your appointments with the psychologist, you talk to your girlfriend about everything and she tells you that you should choose a job.')
      input()
      Job=(input('Which job will you choose?a)assistant or b)animator')) 
      if Job=="assistant":
        input()
        print('You are good at your job but you do not like it')
        input()
        print('you marry your girlfriend, you get old, you die but you were unhappy in your life because you did not like your job. Game over')

      if Job=="animator":
        input()
        print('you loved your work and you were successful since you were very partying and animated the parties')
        input()
        print('your economic level was good, and you decide to marry your wife')
        input()
        print('You die of depression that your wife died. Game over')
        
      if Hob=="Break":
        print('Your girlfriend, seeing that you did not decide to seek help, she break up with you')
        input()
   
        print('You keep going out to parties with your friends')
        input()
        print('But you remember your girlfriend and start spending all your money on drugs and parties')
        input()
        print('At a party you took too many drugs and died of an overdose. Game over')




if Name=="Iker":
  print('Your caracteristics are: Good at school (Math), you like the medicine career but youre bad at it ')
  print("Hi" ,Name ,"click enter to start your life")
  input()
  print("Your life is about to start, as you know you are good in math and you are in the math team of the school, but at the same our you have a very important class of medicine with a big profesional, you need to make a decision")
  input() 
  IS1=(input('what are you going to do a)math b)medicine'))
  if IS1=="medicine":        
    print('You decide to go to the medicine event')  
    print('You had a great time there')
    print('At the end of the event you have the oportunitie to exchange some words with the profesional medic')
    print('He told you to keep working and he asked you to be his asistant because he saw a big talent in you')
    print('You need to choose of being his asistant or still studying by yourself')
    print('Then the school talk to you and they wanted to give you a scholarship to stay in your team and not study medicine')
    IS2=(input('What decision are you going to take a)math b)medicine c)asistant'))
    if IS2=="math":
      print('You accept the scholarship')
      input()
      print('You still in the school team and tried to improve your level to help the team and your math future')
      print('You choose the bacachos team and the scholarship ')
      input()
      print('That day you have the training of the math team')
      print('You loose the opportunities of have something with the profesional of science ')
      print('You stay at school until you graduate')
      print('There you tried to be a big profesional in math, but the school offers you to be a teacher in there with a lot of money in the way')
      IS3=(input('What are you going to choose a)teacher b)profesional'))
      if IS3=="teacher":
        print('you choose the teacher carrer')
        input()
        print('you start teaching there in the same school and you were the coach of the bacachos team')
        print('you become older and older')
        print('until the school after 10 years of teaching in there')
        print('decided to hire you')
        print('and because you didn’t wanted to learn science, you get a big depression in you')
        print('the rest in your life you lived it in an apartment alone until diying')
        print('end of the story...')
        print('unless????.....')
      if IS3=="profesional":
        print('you choose being a profesional matematic')
        input()
        print('one of you most incredible ideas when you were in college was, how do the universe start?')
        print('you always think that maybe happened another thing except big bang')
        print(' so now being a professional of matematics you called the scientific to make team for searching the reality about the universe')
        print('he accepts and both of you start working in your big proyect')
        print('after 2 years of searching you find out that the multiverse can be real, and you start searching more of it')
        print('so you and your partner wanted to search thing about it and what else can be better than the marvel and DC comics/movies')
        print('but you start complaining about if the multiverse is better on marvel or in DC')
        print('you needed to see only one of those so you choose')
        IS4=(input('What are you going to choose a)marvel b)DC'))
        if IS4=="marvel":
          print('you will see the marvel movies')
          input()
          print('so after year and years of analyzing the movies')
          print('in 2040 you and your partner share to the world the reality of the universe and its like this…')
          print('it excited the marvel universe, but after years and years of fights and superheroesl')
          print('the marvel universe turned into the real universe but all the super heroes killed all the villans and unified to create a new universe without powers') 
          print('and thats the way the universe has been created')
          print('you become the best and most important mathematic in the whole universe’')
          print('end of the story')
          print('maybe you should try another story now')
    
        if IS4=="DC":
          print('you see the DC movies')
          input()
          print('after seeing them you find a little bit of information in it')
          print('and with that information and another one of the media you start searching')
          print('in 2040, you find more information of it')
          print('at 2055, you ended your proyect and discovered the universe origin')
          print('but when you are presenting your job to the world, you notice and error')
          print('your partner forgets to errase something and that thing changes the whole proyect')
          print('that means all your proyect was a farce')
          print('you get depressed and lived in your apartment alone the rest of your life')
          print('end of the story')
          print('marvel is better than DC <3')
    if IS2=="medicine":
      print('You are going to make your carrer alone ')
      print('after finishing the schools after 2 months more') 
      print('you start searching for works in hospitals')
      print('they gived you a work in the hospital named c achondeo')
      print('you went on monday your first day')
      print('after tour first day of work your boss wanted to talk to you')
      print('you enter to his office and he give you a good notice')
      print('he talked to you to a opportunity to change country for attending another hospital ')
      print('that means leaving your whole life and start a new one in a diferent country')
      input()
      IS3=(input('What decision are you going to choose a)stay b)leave'))
      if IS3=="stay":       
        print('you are going to stay in your country') 
        input()
        print('you stay the rest of your life atending in that hospital')
        print('then after some years your became the most important doctor of the hospital' )
        print('you became the chief and then when you died the hospital was renamed with your nickname ')
        print('you dont think is the end of the history right?')
      if IS3=="leave": 
        print('you are going to travel another country')
        input()
        print('you are going to live in alaska')           
        print('you just have 1 week more in mexico to travel and package your things') 
        print('there when you arrived, after a week you died beacuse the cold')     
        print('end of the timeline..............or no?;)')
    if IS2=="asistant":
      print("You are gioing to be the asistant of a big medicine profesional")
      input()
      print('At you first day at work, you talk with the profesional to see and improve your medicine knowledge')
      print('right there you start learning of medicine more than always')
      print('but then the expert realizes than you dont have any talent on medicine at all')
      print('so he literally throw you like garbaje')
      print('after that you cant enter again to the school and to your carrers')
      print('you were ruined and you decided to die by trying to climb the everest')
      print('HAHAHAHA, YOU LITERALLY CHOOSE THE WORST FINAL, SUCH A DUMB ;), by the way you can try other story <3')
      
    
  if IS1=="math":
    print('Ok you are going to go to your competition')
    print('In the competition you give all your answers wrong')
    print('And you loose the competition and they are thinking of get you out of the team')
    input()
    print('Then you loose your oportunitie of learning with one of the biggest medics of the world')
    print('After that the organization of the medicine event call to you to know why you didnt went')
    print('They talk to you because they wanted to see you there because they saw your desire for the medicine carrer')
    print('They asked you to talk about your future at medicine by them')
    print('At the same our you have a math training with your math team called the bacachos')
    IS2=(input('What are you going to do a)math b)medicine'))
    if IS2=="math":
      print('You choose the bacachos team and the scholarship ')
      input()
      print('That day you have the training of the math team')
      print('You loose the opportunities of have something with the profesional of science ')
      print('You stay at school until you graduate')
      print('There you tried to be a big profesional in math, but the school offers you to be a teacher in there with a lot of money in the way')
      IS3=(input('What are you going to choose a)teacher b)profesional'))
      if IS3=="teacher":
        print('you choose the teacher carrer')
        input()
        print('you start teaching there in the same school and you were the coach of the bacachos team')
        print('you become older and older')
        print('until the school after 10 years of teaching in there')
        print('decided to hire you')
        print('and because you didn’t wanted to learn science, you get a big depression in you')
        print('the rest in your life you lived it in an apartment alone until diying')
        print('end of the story...')
        print('unless????.....')
      if IS3=="profesional":
        print('you choose being a profesional matematic')
        input()
        print('one of you most incredible ideas when you were in college was, how do the universe start?')
        print('you always think that maybe happened another thing except big bang')
        print(' so now being a professional of matematics you called the scientific to make team for searching the reality about the universe')
        print('he accepts and both of you start working in your big proyect')
        print('after 2 years of searching you find out that the multiverse can be real, and you start searching more of it')
        print('so you and your partner wanted to search thing about it and what else can be better than the marvel and DC comics/movies')
        print('but you start complaining about if the multiverse is better on marvel or in DC')
        print('you needed to see only one of those so you choose')
        IS4=(input('What are you going to choose a)marvel b)DC'))
        if IS4=="marvel":
          print('you will see the marvel movies')
          input()
          print('so after year and years of analyzing the movies')
          print('in 2040 you and your partner share to the world the reality of the universe and its like this…')
          print('it excited the marvel universe, but after years and years of fights and superheroesl')
          print('the marvel universe turned into the real universe but all the super heroes killed all the villans and unified to create a new universe without powers') 
          print('and thats the way the universe has been created')
          print('you become the best and most important mathematic in the whole universe’')
          print('end of the story')
          print('maybe you should try another story now')
    
        if IS4=="DC":
          print('you see the DC movies')
          input()
          print('after seeing them you find a little bit of information in it')
          print('and with that information and another one of the media you start searching')
          print('in 2040, you find more information of it')
          print('at 2055, you ended your proyect and discovered the universe origin')
          print('but when you are presenting your job to the world, you notice and error')
          print('your partner forgets to errase something and that thing changes the whole proyect')
          print('that means all your proyect was a farce')
          print('you get depressed and lived in your apartment alone the rest of your life')
          print('end of the story')
          print('marvel is better than DC <3')
      
    if IS2=="medicine":
      print('You give an oportunitie to the medicine organization')
      input()
      print('You get there and hear they ideas')
      print('And you had the oportunitie of talk with the profesional')
      print('He asked you of being his asistant because he saw a good level in you')
      print('The school know about that and wanted to give you a scholarship ')
      IS2=(input('What decision are you going to take a)math b)medicine c)asistant'))
      if IS2=="math":
        print('You accept the scholarship and bacachos team')
        input()
        print('That day you have the training of the math team')
        print('You loose the opportunities of have something with the profesional of science ')
        print('You stay at school until you graduate')
        print('There you tried to be a big profesional in math, but the school offers you to be a teacher in there with a lot of money in the way')
        IS3=(input('What are you going to choose a)teacher b)profesional'))
        if IS3=="teacher":
          print('you choose the teacher carrer')
          input()
          print('you start teaching there in the same school and you were the coach of the bacachos team')
          print('you become older and older')
          print('until the school after 10 years of teaching in there')
          print('decided to hire you')
          print('and because you didn’t wanted to learn science, you get a big depression in you')
          print('the rest in your life you lived it in an apartment alone until diying')
          print('end of the story...')
          print('unless????.....')
        if IS3=="profesional":
          print('you choose being a profesional matematic')
          input()
          print('one of you most incredible ideas when you were in college was, how do the universe start?')
          print('you always think that maybe happened another thing except big bang')
          print(' so now being a professional of matematics you called the scientific to make team for searching the reality about the universe')
          print('he accepts and both of you start working in your big proyect')
          print('after 2 years of searching you find out that the multiverse can be real, and you start searching more of it')
          print('so you and your partner wanted to search thing about it and what else can be better than the marvel and DC comics/movies')
          print('but you start complaining about if the multvererse is better on marvel or in DC')
          print('you needed to see only one of those so you choose')
          IS4=(input('What are you going to choose a)marvel b)DC'))
          if IS4=="marvel":
            print('you will see the marvel movies')
            input()
            print('after seeing all of the marvel movies you and your friend recognize that all the things they say are real')
            print('so after year and years of analyzing the movies')
            print('in 2040 you and your partner share to the world the reality of the universe and its like this…')
            print('it excited the marvel universe, but after years and years of fights and superheroesl')
            print('the marvel universe turned into the real universe but all the super heroes killed all the villans and unified to create a new universe without powers') 
            print('and thats the way the universe has been created')
            print('you become the best and most important mathematic in the whole universe’')
            print('end of the story')
            print('maybe you should try another story now')
    

          if IS4=="DC":
            print('you see the DC movies')
            input()
            print('after seeing them you find a little bit of information in it')
            print('and with that information and another one of the media you start searching')
            print('in 2040, you find more information of it')
            print('at 2055, you ended your proyect and discovered the universe origin')
            print('but when you are presenting your job to the world, you notice and error')
            print('your partner forgets to errase something and that thing changes the whole proyect')
            print('that means all your proyect was a farce')
            print('you get depressed and lived in your apartment alone the rest of your life')
            print('end of the story')
            print('marvel is better than DC <3')
    if IS2=="medicine":
      print('You are going to make your carrer alone ')
      print('after finishing the schools after 2 months more')
      print('you start searching for works in hospitals')
      print('they gived you a work in the hospital named cachondeo')
      print('you went on monday your first day')
      print('after tour first day of work your boss wanted to talk to you')
      print('you enter to his office and he give you a good notice')
      print('he talked to you to a opportunity to change country for attending another hospital ')
      print('that means leaving your whole life and start a new one in a diferent country')
      input()
      IS3=(input('What decision are you going to choose a)stay b)leave'))
      if IS3=="stay":       
        print('you are going to stay in your country')
        input()
        print('you stay the rest of your life atending in that hospital')
        print('then after some years your became the most important doctor of the hospital' )
        print('you became the chief and then when you died the hospital was renamed with your nickname ')
        print('you dont think is the end of the history right?')

      if IS3=="leave": 
        print('you are going to travel another country')
        input()
        print('you are going to live in alaska')           
        print('you just have 1 week more in mexico to travel and package your things') 
        print('there when you arrived, after a week you died beacuse the cold')     
        print('end of the timeline..............or no?;)')
        input()
    if IS2=="asistant":
      print("You are gioing to be the asistant of a big medicine profesional")
      input()
      print('At you first day at work, you talk with the profesional to see and improve your medicine knowledge')
      print('right there you start learning of medicine more than always')
      print('but then the expert realizes than you dont have any talent on medicine at all')
      print('so he literally throw you like garbaje')
      print('after that you cant enter again to the school and to your carrers')
      print('you were ruined and you decided to die by trying to climb the everest')
      print('HAHAHAHA, YOU LITERALLY CHOOSE THE WORST FINAL, SUCH A DUMB ;), by the way you can try other story <3')

      
      




if Name=="Daniel":
  print('Your caracteristics are:Good at sports(Soccer and American Football), bad in school but you like it')
  print("Hi", Name ,"click enter to start your life")
  input()
  print("Your life its all about soccer but you prefer studying than playing")
  print('On one afternoon you had an important match of soccer but the next day you have an exam so you need to select what do you prefer')
  input()
  DD1=(input('select what you are going to do a)Soccer match b)Study for the exam '))
  if DD1=="Soccer match":
    print('Perfect your going to the match')
    print('On the match you were bench and your coach thinks you are a goalkeeper')
    print('Your team won but you didnt play because you are new on the team')
    input()
    print('Next day you had your exam but you failed it because you didnt studied ')
    print('After the class finished the teacher asked you to stay with him some minutes more')
    print('The teacher said you needed particular classes on the afternoons to help you ')
    print('That afternoon you had a training and the particular classes')
    DD2=(input('What thing would you like to do a)Training b)Particular classes '))
    
    if DD2=="Training":
      print('You went to training for first time')
      print('Your coach saw you play as a Striker and he see that you have potential ')
      print()
      print('After that you decide that your going to be a professional fooballer')
      print('Next day your couch said you that you could be the starting stricker but you need to spend more time training ')
      print('You started giving more importance to the Soccer than the school ')
      print('You have entered a tournament')
      print('After a month you have been getting better at soccer')
      print('You are on the last months of school and you have your final test.')
      print('At the same time you have the final of your soccer tournament')
      DD3=(input('select what you are going to do a)Soccer match b)Study for tests'))
      
      if DD3=="Soccer match":
        print('On the soccer match you scored a hat trick and you were the PoTM(Player of The Match)')
        print('Thanks to you your team won the tournament ')
        print('On the match they were player recruiters of great teams like Real Madrid, Barcelona and Manchester City. ')
        print('You didnt notice but all of the recruiters were interested on you.')
        print('After the match a person was following you, when you notice you told him "Do you need something"?.')
        print('He responded you by saing "Im a recruiter from Barcelona and I would like to make you part of us".')
        print('You were very exited and you accepted without thinking')
        print('The recruiter said that first you needed to pass some tests')
        print('Good players and professional players completed and passed the tests by spending 3-5 days')
        print('Players that are not well trained and not very prepared took 6-14 days')
        print('In your first day you completed all the tests and you surprised all of the coaches of Barcelona')
        print('Some of them think you will be a great player')
        print('They accepted you after you passed the tests')
        print('You are going to start on the Team B')
        print('You have the motivation and you are going to work hard for months')
        input()
        print('After months your school send you an email saying you can save the school year you failed ')
        print('As usually you dont have good luck and at the same time you have your debut in the Team B of the Barcelona')
        DD4=input('select what you are going to do a)Debut b)School')

        if DD4=="Debut":
          print('On the first half of the match was a very difficult match ')
          print('But on the second half you lead the team to the victory')
          print('On your debut you scored a goal and maked two very good assists')
          input()
          print('After the match all of your teammates thank you by making a great debut')
          print('Next day your couch send you to the First Team')
          print('Your coach has faith on you and he wants to see on what level are you')
          print('You had your first training with the First Team ')
          print('When the First Team started to arrive you were being very nervious')
          print('You started to see football legends')
          print('After the training on eof the Legends talked with your coach')
          print('Then your coach said you that the Team sees potential on you')
          print('From being on the Team B your coach sends you to train with the First Team')
          print('You were very proud of yourself and then on legend came to talk to you')
          print('He said that he would teach all what he knows because he see something on you that remembers himself')
          print('After some months of training everyone thinks you are ready to play a match with the First Team')
          print('On your first season you scored 31 goals on 30 matches ')
          print('With the help of your team and your effort you are getting better every season')
          print('Your next goal is to win the champions league ')
          print('After 3 good years you have your first champions league final ')
          print('On one important play you have to decide what your going to do')
          
          DD5=input('a)Dribble 3 players b)Shoot from distance')
          
          if DD5=="Shoot from distance":
            print('When you decided to shoot some teammates were saying to you to dont shoot')
            print('You didnt care and you shooted')
            print('You scored a 35 yard goal')
            print('Because of your goal your team won the champions league by 1-0')
            print('The Tournament Managers gave you the awards of the Player of The Match')
            print('Player of the Tournament')
            print('The Goalscorer of the Tournament')
            print('After all the awards you remember that your contract with the Club is finishing in that season')
            print('After that you receive a call from the PSG club ')
            print('They said that they wanted you to be part of their proyect to the future of football')
            print('You have the decision to stay on the Club or go to the PSG Club')
            print('FC Barcelona wants to  give you a contract for 3 years and you will earn $15 million per year')
            print('PSG offered a contract for 3 years and an earning of $50 million per year ')
            DD6=input('What club are you going to be part a)Barcelona b)PSG')
            if DD6=="Barcelona":
              print('After you decided to play with the FC Barcelona')
              print('You start a wonderful season ')
              print('In your first season with Barcelona you scored 30 goals on 24 matches ')
              print('On the next seasons you became a legend on the club')
              
              print('Your the goalscorer of the tournament')
              print('On the Champions League final you scored two amazing goals')
              print('You won the Champions League ')
              print('After a great career')
              print('You finish your career with the best record of goals in history')
              print('You scored 852 goals')
              print('And your asists were 369')
              print('You won 41 titles in your career')
              print('Before your retirement you teached all your techniques to the younger')
              print('You retire as a legend on the club ')
              print('All the club made you a farewell')
              print('You cried in your farewell')
              print('You die of old age')

            if DD6=="PSG":
              input()
              print('After selecting the PSG your fans are upset because they say you prefered the money')
              print('After a long career you retire without trophies and a lot of money ')
              print('After your retirement you became a profesional coach')
              print('You became coach of your favorite club')
            
              print('The FC Barcelona')
              print('You won a lot of titles with them and became a legend of the club')
              print('Your dream is to win the next Champions League')
              print('After some years of dedication')
              print('You have the chance of wining the champions league')
              print('Your team won the final ')
              print('You achieved your dream')
              print('You retire as coach after that')
              
            
          if DD5=="Dribble 3 players":
            print('When you start dribbling one of the players')
            input()
            print('That player threw you to the ground causing you an horrible injury')
            print('While you were on the hospital your team losed the match')
            input()
            
            print('The doctors said that you wont be able to walk again in a lot of years')
            input()
            print('Your so depresed because your thinking what you could have been without that injury')
            
            input()
            print('You died of depression')


          if DD4=="School":
            input()
            print('When you were at school you forgot to tie your shoes and when you were going down stairs you fell and die ')

          if DD3=="Study for tests":
           input()
          print('You died unexpectedly')
      
          if DD2=="Particular classes":
           print('You went to your first particular classes')
            
           print('In the particular classes you improved and you learned more')
           input()
           print('While you were in the particular classes it was a school shooting and you died')
          if DD1=="Study for the exam":
            print('Perfect you selected stuying for your exam')
            print()
            print('The next day you went to the school to take the exam')
            print('You passed the test with 60/100, and the teacher wanted to talk with you')
            print('The teacher said to you that you are improving and that you need to effort more to have success')
            input()
            print('Suddendly a car hits you and you die')