print('Hola Mundo')
print('My name is Iker Santiago Vera Blanco')
print('Im in 9C')
print('I dont have favourite food but I like the Itialian Restaurants ')
print('My favourite sport is the American footbal and I play it')
